# Generated by Django 4.1.3 on 2022-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgetpassword', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
